//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightService.Monitor.LightControlReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LightControlReference.IAstoriaLightServiceControl")]
    public interface IAstoriaLightServiceControl {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAstoriaLightServiceControl/UpdateControlledObjects", ReplyAction="http://tempuri.org/IAstoriaLightServiceControl/UpdateControlledObjectsResponse")]
        void UpdateControlledObjects(System.Collections.Generic.List<LightService.Common.LightZone> lightZone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAstoriaLightServiceControl/UpdateControlledObjects", ReplyAction="http://tempuri.org/IAstoriaLightServiceControl/UpdateControlledObjectsResponse")]
        System.Threading.Tasks.Task UpdateControlledObjectsAsync(System.Collections.Generic.List<LightService.Common.LightZone> lightZone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAstoriaLightServiceControl/GetControlledObjects", ReplyAction="http://tempuri.org/IAstoriaLightServiceControl/GetControlledObjectsResponse")]
        System.Collections.Generic.List<LightService.Common.LightZone> GetControlledObjects();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAstoriaLightServiceControl/GetControlledObjects", ReplyAction="http://tempuri.org/IAstoriaLightServiceControl/GetControlledObjectsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<LightService.Common.LightZone>> GetControlledObjectsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAstoriaLightServiceControlChannel : LightService.Monitor.LightControlReference.IAstoriaLightServiceControl, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AstoriaLightServiceControlClient : System.ServiceModel.ClientBase<LightService.Monitor.LightControlReference.IAstoriaLightServiceControl>, LightService.Monitor.LightControlReference.IAstoriaLightServiceControl {
        
        public AstoriaLightServiceControlClient() {
        }
        
        public AstoriaLightServiceControlClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AstoriaLightServiceControlClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AstoriaLightServiceControlClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AstoriaLightServiceControlClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void UpdateControlledObjects(System.Collections.Generic.List<LightService.Common.LightZone> lightZone) {
            base.Channel.UpdateControlledObjects(lightZone);
        }
        
        public System.Threading.Tasks.Task UpdateControlledObjectsAsync(System.Collections.Generic.List<LightService.Common.LightZone> lightZone) {
            return base.Channel.UpdateControlledObjectsAsync(lightZone);
        }
        
        public System.Collections.Generic.List<LightService.Common.LightZone> GetControlledObjects() {
            return base.Channel.GetControlledObjects();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<LightService.Common.LightZone>> GetControlledObjectsAsync() {
            return base.Channel.GetControlledObjectsAsync();
        }
    }
}
